### ISSUE TITLE
consider adding ability to drop root privileges after binding to port <1000

### ISSUE THREAD

**Issue by mkeedlinger** [mkeedlinger/locket#1]
[this](https://thomashunter.name/blog/drop-root-privileges-in-node-js/) is how to do it.

Important info and warnings about doing so
- https://news.ycombinator.com/item?id=4873139
- https://www.reddit.com/r/node/comments/14a3dv/drop_root_privileges_in_nodejs_after_binding_to/

**Comment by janka102** [comment]
Yeah it seems like the nginx/haproxy method or authbind would be a bit better. It seems authbind has less configuration and less restrictions (there were mentions of websocket issues with nginx). I've used nginx to do this before and it works great (never tried with websockets though), but that authbind thing seems worth looking into.

On a slight tangent, but still about running Node, there is [pm2](http://pm2.keymetrics.io) which can be used to manage the process and create a startup script so it runs when the server boots.

**Comment by mkeedlinger** [comment]
Re dropping root privileges, I was think to include this for those who ignore the warning and run as root because it requires less configuring.

With PM2, I think that would be great, but how would that integrate with PKG?
